/**
 * Demo-only product data when Supabase is not configured (local dev without env).
 * When DB is available, the app uses `products` table data only — no sample merge.
 */
export function getSampleProducts() {
  return [
    {
      id: '1',
      name: 'Classic Aviator Sunglasses',
      price: 2999,
      originalPrice: 3999,
      image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500',
      category: 'sunglasses',
      brand: 'EYE10',
      discount: 25,
      frameType: 'Full Rim',
      description:
        'Timeless aviator design with UV protection and premium metal frame. Perfect for everyday wear.',
    },
    {
      id: '2',
      name: 'Round Frame Glasses',
      price: 2499,
      originalPrice: 2999,
      image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500',
      category: 'glasses',
      brand: 'EYE10',
      discount: 17,
      frameType: 'Full Rim',
      description:
        'Vintage-inspired round frames perfect for a classic look. Lightweight and comfortable.',
    },
    {
      id: '3',
      name: 'Cat Eye Sunglasses',
      price: 3499,
      image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500',
      category: 'sunglasses',
      brand: 'Ray-Ban',
      frameType: 'Full Rim',
      description: 'Elegant cat-eye design with polarized lenses and stylish frame.',
    },
    {
      id: '4',
      name: 'Square Frame Glasses',
      price: 2199,
      image: 'https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?w=500',
      category: 'glasses',
      brand: 'EYE10',
      frameType: 'Full Rim',
      description: 'Modern square frames with anti-glare coating and lightweight design.',
    },
    {
      id: '5',
      name: 'Wayfarer Sunglasses',
      price: 2799,
      originalPrice: 3499,
      image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500',
      category: 'sunglasses',
      brand: 'Oakley',
      discount: 20,
      frameType: 'Full Rim',
      description: 'Iconic wayfarer style with durable acetate frame and UV400 protection.',
    },
    {
      id: '6',
      name: 'Oval Frame Glasses',
      price: 2299,
      image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500',
      category: 'glasses',
      brand: 'EYE10',
      frameType: 'Full Rim',
      description: 'Comfortable oval frames with blue light filter technology.',
    },
    {
      id: '7',
      name: 'Rimless Glasses',
      price: 1899,
      originalPrice: 2499,
      image: 'https://images.unsplash.com/photo-1524594152303-9fd13543fe6e?w=500',
      category: 'glasses',
      brand: 'Gucci',
      discount: 24,
      frameType: 'Rimless',
      description: 'Ultra-lightweight rimless design for maximum comfort and style.',
    },
    {
      id: '8',
      name: 'Sport Sunglasses',
      price: 4499,
      image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500',
      category: 'sunglasses',
      brand: 'Oakley',
      frameType: 'Full Rim',
      description: 'High-performance sports sunglasses with impact-resistant lenses.',
    },
    {
      id: '9',
      name: 'Browline Glasses',
      price: 2699,
      originalPrice: 3299,
      image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500',
      category: 'glasses',
      brand: 'Prada',
      discount: 18,
      frameType: 'Browline',
      description: 'Sophisticated browline frames combining metal and acetate materials.',
    },
    {
      id: '10',
      name: 'Oversized Sunglasses',
      price: 3799,
      image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500',
      category: 'sunglasses',
      brand: 'Versace',
      frameType: 'Full Rim',
      description: 'Luxury oversized sunglasses with gradient lenses and designer frame.',
    },
    {
      id: '11',
      name: 'Classic Analog Watch',
      price: 4999,
      originalPrice: 5999,
      image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=500',
      category: 'watches',
      brand: 'Titan',
      discount: 17,
      description: 'Elegant stainless steel analog watch with a genuine leather strap and scratch-resistant glass.',
    },
    {
      id: '12',
      name: 'Chronograph Steel Watch',
      price: 7999,
      image: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=500',
      category: 'watches',
      brand: 'Fossil',
      description: 'Bold chronograph dial with a stainless steel bracelet, built for everyday wear.',
    },
    {
      id: '13',
      name: 'Digital Sports Watch',
      price: 2499,
      originalPrice: 2999,
      image: 'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=500',
      category: 'watches',
      brand: 'Casio',
      discount: 17,
      description: 'Durable digital sports watch with backlight, alarm, and water resistance.',
    },
    {
      id: '14',
      name: 'Minimalist Slim Watch',
      price: 3499,
      image: 'https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=500',
      category: 'watches',
      brand: 'Fastrack',
      description: 'Slim, minimalist dial with a soft leather strap for a refined everyday look.',
    },
    {
      id: '15',
      name: "Women's Rose Gold Watch",
      price: 5499,
      originalPrice: 6499,
      image: 'https://images.unsplash.com/photo-1548169874-53e85f753f1e?w=500',
      category: 'watches',
      brand: 'Titan',
      discount: 15,
      description: 'Rose gold-tone case with a mesh strap and mother-of-pearl dial.',
    },
    {
      id: '16',
      name: 'Automatic Mechanical Watch',
      price: 12999,
      image: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=500',
      category: 'watches',
      brand: 'Fossil',
      description: 'Self-winding automatic movement visible through an exhibition case back.',
    },
  ]
}

export function getSampleProductById(id) {
  return getSampleProducts().find((p) => String(p.id) === String(id)) || null
}
